I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 386, in script
    if Hausis == "Entschuldigt":
  File "game/script.rpy", line 386, in <module>
    if Hausis == "Entschuldigt":
NameError: name 'Hausis' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 386, in script
    if Hausis == "Entschuldigt":
  File "C:\Users\laris\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 1898, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\laris\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\laris\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 386, in <module>
    if Hausis == "Entschuldigt":
NameError: name 'Hausis' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Visual Identity 1.0
Fri Jul 22 12:21:03 2022
